### ISSUE TITLE
Style and other commands for spackbot

### ISSUE THREAD

**Issue by vsoch** [spack/spackbot#8]
from discussion with @tgamblin 

## Spack Bot Style

- [x] comment on PRs with failed style checks and say “hey you can run spack style --fix to fix this!  Or you can just say ‘@spackbot fix style!’ and I’ll do it” #11 
- [x] magically fix PRs and push a commit by the PR author with the fixes if they opt for the latter) #11 
- [x]  say it fixed it and say “you need to pull to get the fix!” #11

## Spackbot commands

- [ ] the bot should respond to comments like “hey @spackbot look at this PR”

## Spack Style

- [x] (this would make it easier for spackbot likely, but isn't directly related to spackbot, putting it here so I remember)

spack style to bootstrap python dependencies like we bootstrap clingo (but easier — no native stuff) so that users don’t need to install anything to use it

This should be satisfied by https://github.com/spack/spack/pull/24819

## Pipelines

- [x] “hey @spackbot re-run the pipeline!” --> spackbot makes an API call to gitlab to re-run that PR’s pipeline #12

**Comment by adamjstewart** [comment]
Most of these are complete. Can we close this issue?

**Comment by alalazo** [comment]
Closing as complete. We can reopen if need be.
